drop down menu added pull request for issue #45
anicmarko9/eu-tours pull request #48
Opened 2023-07-04 06:14 UTC by nazrul7711

hey @anicmarko9  i have added the features this is how it now looks like 
<img width="1440" alt="Screenshot 2023-07-04 at 11 23 02 AM" src="https://github.com/anicmarko9/eu-tours/assets/49507714/be8734a1-c753-4000-95e1-a7f5734b7531">
<img width="1440" alt="Screenshot 2023-07-04 at 11 28 32 AM" src="https://github.com/anicmarko9/eu-tours/assets/49507714/24b0e21b-0c50-4310-abc5-4a3477adc986">

2023-07-04 08:04 UTC, anicmarko9 requested changes
I've updated your changes to guide you in the right direction. See them and implement in your code, and make the PR.

- With these changes, the subLinks are breaking text into two rows. You need to apply CSS to either make font smaller, or make container absolute and stretchable.
- With these changes, CSS in hamburger menu needs adjustments, I'm specifically talking about this line of updated code in HeaderLinkGroup.tsx:
```tsx
                 {subLinks.map(
                      ({ subLink, subTitle }, index: number): JSX.Element => (
                        <li key={`${subLink}-${index}`}>
                          <Link
                            className={`hoverEffect ${
                              isHamburger ? "hover:text-secondary" : "p-3"
                            }`}
                            href={subLink}
                          >
                            {subTitle}
                          </Link>
                        </li>
                      )
                    )}
```

2023-07-05 03:56 UTC, nazrul7711 commented on src/components/links/HeaderLinkGroup.tsx
updated

2023-07-05 04:37 UTC, nazrul7711 commented
i have modified the css and after making changes that u suggested the text is not broken this is the preview don't worry about the background of drop down menu I will change it.
plz also guide me about the doubt I have about hamburger menu I made a comment about that .
<img width="1440" alt="Screenshot 2023-07-05 at 10 04 08 AM" src="https://github.com/anicmarko9/eu-tours/assets/49507714/915b8c66-d7df-4b1f-bc48-156d41f320fa">

2023-07-05 16:43 UTC, anicmarko9 commented
You can design however you think it's the easiest way. But my point was that I don't want to **hover** over Hamburger Menu Icon and see Nav links like that. There is already clickable functionality, so when you **click** on the menu, it will display container with Nav links all over the screen. I wanted to make **hover** effects on those links that show up, not on a **Hamburger Icon**.

I don't have anything specific in mind about those hover effects, so do whatever you like.

2023-07-06 07:54 UTC, nazrul7711 commented
ok I will do the needful.

On Wed, Jul 5, 2023 at 10:13 PM Marko Anić ***@***.***> wrote:

> You can design however you think it's the easiest way. But my point was
> that I don't want to *hover* over Hamburger Menu Icon and see Nav links
> like that. There is already clickable functionality, so when you *click*
> on the menu, it will display container with Nav links all over the screen.
> I wanted to make *hover* effects on those links that show up, not on a *Hamburger
> Icon*.
>
> I don't have anything specific in mind about those hover effects, so do
> whatever you like.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/anicmarko9/eu-tours/pull/48#issuecomment-1622121877>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALZW3ARF3O7JUTOOQLTMGHDXOWKULANCNFSM6AAAAAAZ5H6LBA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-07 21:11 UTC, anicmarko9 approved these changes
I'll approve this without testing.

Why are sublinks empty? In Header.tsx you should put each sublink like this:
```diff
+ subLinks: [
+   { subLink: "/faq", subTitle: "FAQs" },
+   { subLink: "/support", subTitle: "Support Center" },
+   { subLink: "/contact", subTitle: "Contact Us" },
+ ]
```

Sublinks titles are similar to ones in Footer.tsx

2023-07-07 21:15 UTC, merged